repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100000"]
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
        exclude: ^.*\.ipynb$
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: sort-simple-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
    # -   id: ...
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--line-length=100"]
        language_version: python3.9
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies:
        - 'types-requests'
        - 'types-PyYAML'
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D104,D107,D203,D204,D213,D215,D400,D401,D404,D406,D407,D408,D409,D413 # enforces google style docstrings: https://www.pydocstyle.org/en/stable/error_codes.html#default-conventions
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
  - repo: local
    hooks:
    - id: flake8
      name: flake8 (with docstring_verifier)
      entry: flake8
      language: python
      types: [python]
      args: ["--max-line-length=100", "--ignore=E501,W503,W605,E203,E402"]
      additional_dependencies:
      -   ./
